[EVDEV]
# Interpret KEY_WAKEUP as if it were KEY_POWER.
# When received from touchscreen input device it will
# then be handled as double tap wakeup within mce.
KEY_WAKEUP=KEY_POWER

[DoubleTap]
ControlPath = /sys/devices/platform/soc/c84000.spi/spi_master/spi2/spi2.0/panel_info/double_tap_wake
EnableValue = 1
DisableValue = 0

