[ffmemless]

# System wide effect settings file evironment variable.
# The if there are parameters for any effects in the system settings file
# pointed by the given environment variable, they will override the effect
# settings for those effects. Other effects remain unchanged.
system_effects_env = NGF_FFMEMLESS_SETTINGS

# EXAMPLE: re-define NGF_SHORT in system settings file
# export NGF_FFMEMLESS_SETTINGS=/path/to/my/feedback.ini
# contents of "feedback.ini" would look like this
#[ffmemless]
#NGF_SHORT_TYPE = rumble
#NGF_SHORT_DURATION = 110
#NGF_SHORT_DELAY = 1
#NGF_SHORT_MAGNITUDE = 56000
#
# Please note that the [ffmemless] tag is needed for glib to find the effects.
# Now this will change the NGF_SHORT settings to what they are above.


# All effect names must be listed here, otherwise they don't get created
supported_effects = touch;touch_weak;touch_strong;release;release_weak;release_strong;drag_start;drag_fail;drag_boundary;drag_end;short;strong;long;notice;message;attention;alarm;ringtone

# Setting up the effect parameters.
# - The only mandatory parameter is _TYPE, if it's missing effect is not created
# - Full list of valid parameter value ranges below
#
# - Generic parameters for all effect types
#
# _TYPE =	[rumble|periodic], no default, mandatory parameter
# _DIRECTION = 	[forward|reverse], defaults to forward
# _DURATION = 	[0,65535], milliseconds, defaults to NGF_DEFAULT_DURATION
# _DELAY = 	[0,65535], milliseconds before starting playback, defaults to 0
#
# _REPEAT =	[1,4294967295], how many times to repeat effect, defaults to 1
#		Please note that if the event has "sound.repeat" enabled,
#		the effect is repeated until stop signal regardless of _REPEAT
#		value.
#
# - Type specific parameters for rumble effects:
#
# _MAGNITUDE =	[0,65535], defaults to NGF_DEFAULT_RMAGNITUDE
#
# -Type specific parameters for periodic effects
#
# _WAVEFORM =	[sine|triangle|square], defaults to sine
# _PERIOD =	[0,65535], defaults to 0
# _MAGNITUDE =	[0,32767], defaults to NGF_DEFAULT_PMAGNITUDE
# _OFFSET =	[0,32767], defaults to 0
# _PHASE =	[0,65535], in milliseconds, defaults to 0
# _ATTACK =	[0,65535], in milliseconds, defaults to 0
# _ALEVEL =	[0,32767], defaults to 0
# _FADE =	[0,65535], in milliseconds, defaults to 0
# _FLEVEL =	[0,32767], defaults to 0

touch_TYPE = rumble
touch_DURATION = 40
touch_DELAY = 0
touch_MAGNITUDE = 24000

touch_weak_TYPE = rumble
touch_weak_DURATION = 40
touch_weak_DELAY = 0
touch_weak_MAGNITUDE = 20000

touch_strong_TYPE = rumble
touch_strong_DURATION = 40
touch_strong_DELAY = 0
touch_strong_MAGNITUDE = 30000

release_TYPE = rumble
release_DURATION = 20
release_DELAY = 0
release_MAGNITUDE = 24000

release_weak_TYPE = rumble
release_weak_DURATION = 20
release_weak_DELAY = 0
release_weak_MAGNITUDE = 20000

release_strong_TYPE = rumble
release_strong_DURATION = 20
release_strong_DELAY = 0
release_strong_MAGNITUDE = 30000

drag_start_TYPE = rumble
drag_start_DURATION = 20
drag_start_DELAY = 0
drag_start_MAGNITUDE = 25000

drag_fail_TYPE = rumble
drag_fail_DURATION = 25
drag_fail_DELAY = 0
drag_fail_MAGNITUDE = 25000

drag_boundary_TYPE = rumble
drag_boundary_DURATION = 30
drag_boundary_DELAY = 0
drag_boundary_MAGNITUDE = 25000

drag_end_TYPE = rumble
drag_end_DURATION = 40
drag_end_DELAY = 0
drag_end_MAGNITUDE = 25000

short_TYPE = rumble
short_DURATION = 80
short_DELAY = 0
short_MAGNITUDE = 24000

strong_TYPE = rumble
strong_DURATION = 80
strong_DELAY = 0
strong_MAGNITUDE = 65535

long_TYPE = rumble
long_DURATION = 850
long_MAGNITUDE = 65535

notice_TYPE = rumble
notice_DURATION = 100
notice_REPEAT = 2
notice_DELAY = 500
notice_MAGNITUDE = 40000

message_TYPE = rumble
message_DURATION = 240
message_REPEAT = 2
message_DELAY = 140
message_MAGNITUDE = 35000

attention_TYPE = rumble
attention_DURATION = 100
attention_REPEAT = 3
attention_DELAY = 100
attention_MAGNITUDE = 35000

alarm_TYPE = rumble
alarm_DURATION = 4000
alarm_DELAY = 500
alarm_MAGNITUDE = 40000

ringtone_TYPE = rumble
ringtone_DURATION = 2400
ringtone_DELAY = 400
ringtone_MAGNITUDE = 50000

